# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: bdf5b2b027934632ed257c7ef50da3fd98802ba0da3071d1238a5ae2c7c1ffd232a729eb2637d24c1d42060f813eaafc7649998d0915421fa3831b4d7c2a3400

test:
  secret_key_base: 3cbdfe610cbaf3afe57a0e2683376849f320e868eef7a8b7f38c221405aef9a750d46607d60e288a5523c6c862015fe59595187ad54d81382bcb10e0c84abdc9

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
